### ISSUE TITLE
Allow production fallback on development api-server failure

### ISSUE THREAD

**Issue by jcunliffe1** [tolgee/tolgee-js#2130]
Currently a failure in fetching leads to another failure in scopes. Then the application stops, when really it could just load the provided static data:

{code}

    NgxTolgeeModule.forRoot({
      preloadFallback: true,
      staticData: {
        // @ts-ignore
        en: () => import("../assets/i18n/en.json"),
        // @ts-ignore
        de: () => import("../assets/i18n/de.json"),
      },
      apiUrl: environment.tolgeeApiUrl,
      apiKey: environment.tolgeeApiKey,
      ui: environment.tolgeeApiKey ? UI : undefined,
      // forceLanguage: 'en-GB'
    })

{code}

It would be nice if we could have this fall-back to static data, since our api server is turned off sometimes.

**TypeError: Failed to fetch**
    at <anonymous>:1:876
    at zone.js:1523:1
    at proto.<computed> (zone.js:1015:1)
    at e.<anonymous> (ApiHttpService.ts:48:45)
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new ZoneAwarePromise (zone.js:1340:1)
    at r (tslib.es6.js:72:12)
    at e.fetch (ApiHttpService.ts:39:16)
(anonymous) @ CoreService.ts:55
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
a @ tslib.es6.js:74
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ ng_zone.ts:390
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
onScheduleTask @ zone.js:311
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
resolvePromise @ zone.js:1246
(anonymous) @ zone.js:1162
Promise.then (async)
(anonymous) @ zone.js:1514
ZoneAwarePromise @ zone.js:1340
Ctor.then @ zone.js:1513
(anonymous) @ ApiHttpService.ts:48
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetch @ ApiHttpService.ts:39
(anonymous) @ ApiHttpService.ts:61
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetchJson @ ApiHttpService.ts:59
(anonymous) @ CoreService.ts:50
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.getApiKeyDetails @ CoreService.ts:44
(anonymous) @ CoreService.ts:80
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.loadApiKeyDetails @ CoreService.ts:74
(anonymous) @ Tolgee.ts:149
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.run @ Tolgee.ts:143
(anonymous) @ translate.service.ts:30
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
start @ translate.service.ts:27
(anonymous) @ translations-provider.ts:12
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
load @ translations-provider.ts:11
(anonymous) @ ngx-tolgee.module.ts:26
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
(anonymous) @ ngx-tolgee.module.ts:26
runInitializers @ application_init.ts:125
(anonymous) @ application_ref.ts:370
_callAndReportToErrorHandler @ application_ref.ts:479
(anonymous) @ application_ref.ts:368
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
run @ ng_zone.ts:184
bootstrapModuleFactory @ application_ref.ts:349
(anonymous) @ application_ref.ts:406
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
bootstrapModule @ application_ref.ts:406
4431 @ main.ts:154
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ country-profile.mock.ts:44
(anonymous) @ country-profile.mock.ts:44
__webpack_require__.O @ chunk loaded:23
(anonymous) @ country-profile.mock.ts:44
webpackJsonpCallback @ jsonp chunk loading:70
(anonymous) @ main.js:1
Show 63 more frames
**CoreService.ts:57 Error getting scopes. Trying to switch to production mode!**
(anonymous) @ CoreService.ts:57
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
a @ tslib.es6.js:74
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ ng_zone.ts:390
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
onScheduleTask @ zone.js:311
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
resolvePromise @ zone.js:1246
(anonymous) @ zone.js:1162
Promise.then (async)
(anonymous) @ zone.js:1514
ZoneAwarePromise @ zone.js:1340
Ctor.then @ zone.js:1513
(anonymous) @ ApiHttpService.ts:48
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetch @ ApiHttpService.ts:39
(anonymous) @ ApiHttpService.ts:61
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetchJson @ ApiHttpService.ts:59
(anonymous) @ CoreService.ts:50
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.getApiKeyDetails @ CoreService.ts:44
(anonymous) @ CoreService.ts:80
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.loadApiKeyDetails @ CoreService.ts:74
(anonymous) @ Tolgee.ts:149
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.run @ Tolgee.ts:143
(anonymous) @ translate.service.ts:30
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
start @ translate.service.ts:27
(anonymous) @ translations-provider.ts:12
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
load @ translations-provider.ts:11
(anonymous) @ ngx-tolgee.module.ts:26
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
(anonymous) @ ngx-tolgee.module.ts:26
runInitializers @ application_init.ts:125
(anonymous) @ application_ref.ts:370
_callAndReportToErrorHandler @ application_ref.ts:479
(anonymous) @ application_ref.ts:368
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
run @ ng_zone.ts:184
bootstrapModuleFactory @ application_ref.ts:349
(anonymous) @ application_ref.ts:406
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
bootstrapModule @ application_ref.ts:406
4431 @ main.ts:154
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ country-profile.mock.ts:44
(anonymous) @ country-profile.mock.ts:44
__webpack_require__.O @ chunk loaded:23
(anonymous) @ country-profile.mock.ts:44
webpackJsonpCallback @ jsonp chunk loading:70
(anonymous) @ main.js:1
Show 63 more frames
**errors.ts:30 ERROR TypeError: Cannot read properties of undefined (reading 'scopes')**
    at e.<anonymous> (CoreService.ts:83:58)
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at s (tslib.es6.js:73:58)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (ng_zone.ts:405:29)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
defaultErrorLogger @ errors.ts:30
handleError @ error_handler.ts:52
(anonymous) @ application_ref.ts:482
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
runOutsideAngular @ ng_zone.ts:231
(anonymous) @ application_ref.ts:482
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
onInvokeTask @ ng_zone.ts:390
ZoneDelegate.invokeTask @ zone.js:433
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
onScheduleTask @ zone.js:311
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
resolvePromise @ zone.js:1246
(anonymous) @ zone.js:1162
Promise.then (async)
(anonymous) @ zone.js:1514
ZoneAwarePromise @ zone.js:1340
Ctor.then @ zone.js:1513
(anonymous) @ ApiHttpService.ts:48
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetch @ ApiHttpService.ts:39
(anonymous) @ ApiHttpService.ts:61
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.fetchJson @ ApiHttpService.ts:59
(anonymous) @ CoreService.ts:50
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.getApiKeyDetails @ CoreService.ts:44
(anonymous) @ CoreService.ts:80
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.loadApiKeyDetails @ CoreService.ts:74
(anonymous) @ Tolgee.ts:149
(anonymous) @ tslib.es6.js:102
(anonymous) @ tslib.es6.js:83
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
r @ tslib.es6.js:72
e.run @ Tolgee.ts:143
(anonymous) @ translate.service.ts:30
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
start @ translate.service.ts:27
(anonymous) @ translations-provider.ts:12
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
load @ translations-provider.ts:11
(anonymous) @ ngx-tolgee.module.ts:26
(anonymous) @ tslib.es6.js:76
ZoneAwarePromise @ zone.js:1340
__awaiter @ tslib.es6.js:72
(anonymous) @ ngx-tolgee.module.ts:26
runInitializers @ application_init.ts:125
(anonymous) @ application_ref.ts:370
_callAndReportToErrorHandler @ application_ref.ts:479
(anonymous) @ application_ref.ts:368
ZoneDelegate.invoke @ zone.js:400
onInvoke @ ng_zone.ts:405
ZoneDelegate.invoke @ zone.js:399
Zone.run @ zone.js:160
run @ ng_zone.ts:184
bootstrapModuleFactory @ application_ref.ts:349
(anonymous) @ application_ref.ts:406
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
bootstrapModule @ application_ref.ts:406
4431 @ main.ts:154
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ country-profile.mock.ts:44
(anonymous) @ country-profile.mock.ts:44
__webpack_require__.O @ chunk loaded:23
(anonymous) @ country-profile.mock.ts:44
webpackJsonpCallback @ jsonp chunk loading:70
(anonymous) @ main.js:1
Show 66 more frames
**main.ts:155 TypeError: Cannot read properties of undefined (reading 'scopes')**
    at e.<anonymous> (CoreService.ts:83:58)
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at s (tslib.es6.js:73:58)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (ng_zone.ts:405:29)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)

**Comment by jcunliffe1** [comment]
Never mind - this was fixed simply by updating to the most recent 3.5.0
