### ISSUE TITLE
SSR with i18next

### ISSUE THREAD

**Issue by wodka** [tolgee/tolgee-js#3106]
currently during SSR the following are thrown:

```
error - uncaughtException: ReferenceError: document is not defined
    at Function.<anonymous> (/node_modules/@tolgee/core/dist/tolgee.cjs.js:1297:21)
    at step (/node_modules/@tolgee/core/dist/tolgee.cjs.js:79:23)
    at Object.next (/node_modules/@tolgee/core/dist/tolgee.cjs.js:60:53)
    at Function.from (<anonymous>)
    at Function.NodeHelper.evaluate (/node_modules/@tolgee/core/dist/tolgee.cjs.js:1240:22)
    at AttributeHandler.<anonymous> (/node_modules/@tolgee/core/dist/tolgee.cjs.js:2781:44)
    at step (/node_modules/@tolgee/core/dist/tolgee.cjs.js:79:23)
    at Object.next (/node_modules/@tolgee/core/dist/tolgee.cjs.js:60:53)
    at /node_modules/@tolgee/core/dist/tolgee.cjs.js:53:71
    at new Promise (<anonymous>)
ReferenceError: window is not defined
    at Messages.startListening (/ode_modules/@tolgee/core/dist/tolgee.cjs.js:1864:13)
    at PluginManager.run (/node_modules/@tolgee/core/dist/tolgee.cjs.js:1823:27)
    at Tolgee.<anonymous> (/node_modules/@tolgee/core/dist/tolgee.cjs.js:3174:83)
    at step (/node_modules/@tolgee/core/dist/tolgee.cjs.js:79:23)
    at Object.next (/node_modules/@tolgee/core/dist/tolgee.cjs.js:60:53)
    at fulfilled (/node_modules/@tolgee/core/dist/tolgee.cjs.js:50:58)
    at runMicrotasks (<anonymous>)
```

usage is through i18next in nextjs12 with react18

**Comment by stepan662** [comment]
Hey, @wodka. Could you share a code which initializes i18next and tolgee?

**Comment by wodka** [comment]
I will try to put a repo for this together

**Comment by JanCizmar** [comment]
Is this fixed? @stepan662

**Comment by wodka** [comment]
:/ I still haven't put together a repo - will check later today if it is still happening for me

**Comment by JanCizmar** [comment]
Try it with 5.2.0. It will be fixed, I guess.

**Comment by wodka** [comment]
:/ ok, I cannot confirm that it is working now, our instance is stuck on 2.x as we are running a custom with crdb. (the error I have is presumably the missmatch of an older server with the newer js)

**Comment by JanCizmar** [comment]
Hmm, we didn't any breaking change in the dev-tools API from 2.x to 3.x

**Comment by wodka** [comment]
:/ ok, then I investigate further what is happening there

**Comment by wodka** [comment]
ok, it is working - error is coming from `observerType: 'invisible'` - once I switch this to `text` it does work.
