### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'FormatIcu')

### ISSUE THREAD

**Issue by WilliamMayor** [tolgee/tolgee-js#3154]
Hey, I'm 90% certain this is me doing something wrong, so apologies for that.

I can't get the ICU formatter working with my app. I'm using SvelteKit. It works if I use the simple formatter.

Here's my config:

```
import { FormatIcu } from '@tolgee/format-icu';
const tolgee = Tolgee()
    .use(DevTools())
    .use(FormatIcu())
    .init({
        language: 'en',
        // for development
        apiUrl: PUBLIC_TOLGEE_API_URL,
        apiKey: PUBLIC_TOLGEE_API_KEY,
        // for production
        staticData: {
            'ar': () => import('../locales/ar.json'),
            'en': () => import('../locales/en.json'),
        }
    });
```
    
Which results in this stack trace (when running the local dev server):

```
TypeError: Cannot read properties of undefined (reading 'FormatIcu')
    at +layout.svelte:20:16
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at root.svelte:44:39
    at $$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1900:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:116:27)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:303:10)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:363:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:20)
    at async file:///workdir/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:495:22
TypeError: Cannot read properties of undefined (reading 'FormatIcu')
    at +layout.svelte:20:16
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at root.svelte:44:39
    at $$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1900:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:116:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.respond_with_error (/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:82:10)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:322:10)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:363:17)
```

`FormatIcu` is `undefined`?

Thanks for your help!

**Comment by stepan662** [comment]
No you are are right it's a problem with latest svelte kit. I'll prepare a fix

**Comment by WilliamMayor** [comment]
Thanks! Is there anything I can do to help?

**Comment by stepan662** [comment]
No worries I'm already on it
